### ISSUE TITLE
Infinite loop after logging back in

### ISSUE THREAD

**Issue by sherlockwisdom** [smswithoutborders/SMSWithoutBorders.com#67] opened 2023-01-05 16:25 UTC
Can be reproduced by letting a user's session expire and they get automatically logged out. Once user logs back in they're met with an loop that sometimes leads to blank page and other times opens up the page before the automatic log out.

**Comment by nSedrickm** [comment] 2023-01-11 17:20
Hey @sherlockwisdom, I've tested but could not reproduce this issue. Could you please try again and share how it happens?

**Comment by sherlockwisdom** [comment] 2023-01-11 19:10
I will update with better specifics once I reproduce again - noting each steps and pages

**Comment by PromiseFru** [comment] 2023-07-26 11:40
Hi there,

Since there hasn't been any new activity or updates for a while now on this issue, I'll be closing it as resolved. However, if you're still running into this problem or have other relevant details to add, you can reopen this issue or open a new one. 

Thanks

**Closed by PromiseFru** 2023-07-26 11:40 UTC
Labels: bug, help wanted
